/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientmanagementsystem.Patients;

import patientmanagementsystem.Login_Form;

/**
 *
 * @author cex
 */
public class Patient_MainForm extends javax.swing.JFrame {

    /**
     * Creates new form Patient_MainForm
     */
    public Patient_MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CheckPrescription = new javax.swing.JButton();
        jButton_ViewHistory = new javax.swing.JButton();
        jButton_RequestAccountRemoval = new javax.swing.JButton();
        jButton_ViewAppointment = new javax.swing.JButton();
        jButton_AppointmentRequest = new javax.swing.JButton();
        jButton_RateDoctor = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Patient");

        CheckPrescription.setText("Check Prescription");
        CheckPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPrescriptionActionPerformed(evt);
            }
        });

        jButton_ViewHistory.setText("View History");
        jButton_ViewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewHistoryActionPerformed(evt);
            }
        });

        jButton_RequestAccountRemoval.setText("Request Account Removal");
        jButton_RequestAccountRemoval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RequestAccountRemovalActionPerformed(evt);
            }
        });

        jButton_ViewAppointment.setText("View Appointment");
        jButton_ViewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewAppointmentActionPerformed(evt);
            }
        });

        jButton_AppointmentRequest.setText("Appointment Request");
        jButton_AppointmentRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AppointmentRequestActionPerformed(evt);
            }
        });

        jButton_RateDoctor.setText("Rate Doctor");
        jButton_RateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RateDoctorActionPerformed(evt);
            }
        });

        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jButton_Back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jButton_ViewAppointment))
                            .addComponent(jButton_AppointmentRequest, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_RateDoctor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_RequestAccountRemoval)
                            .addComponent(jButton_ViewHistory)
                            .addComponent(CheckPrescription))))
                .addGap(0, 116, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckPrescription)
                    .addComponent(jButton_ViewAppointment))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AppointmentRequest)
                    .addComponent(jButton_RequestAccountRemoval))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ViewHistory)
                    .addComponent(jButton_RateDoctor))
                .addGap(35, 35, 35)
                .addComponent(jButton_Back)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ViewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewAppointmentActionPerformed
        
        ViewAppointment_Form pmf = new ViewAppointment_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_ViewAppointmentActionPerformed

    private void jButton_RateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RateDoctorActionPerformed
        RateDoctor_Form pmf = new RateDoctor_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_RateDoctorActionPerformed

    private void CheckPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPrescriptionActionPerformed
        CheckPrescription_Form pmf = new CheckPrescription_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_CheckPrescriptionActionPerformed

    private void jButton_AppointmentRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AppointmentRequestActionPerformed
        AppointmentRequest_Form pmf = new AppointmentRequest_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_AppointmentRequestActionPerformed

    private void jButton_ViewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewHistoryActionPerformed
        ViewHistory_Form pmf = new ViewHistory_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_ViewHistoryActionPerformed

    private void jButton_RequestAccountRemovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RequestAccountRemovalActionPerformed
        RequestAccountRemoval_Form pmf = new RequestAccountRemoval_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_RequestAccountRemovalActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        setVisible(false);
        Login_Form pmf = new Login_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient_MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckPrescription;
    private javax.swing.JButton jButton_AppointmentRequest;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_RateDoctor;
    private javax.swing.JButton jButton_RequestAccountRemoval;
    private javax.swing.JButton jButton_ViewAppointment;
    private javax.swing.JButton jButton_ViewHistory;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
