/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patientmanagementsystem.Administrators;

import patientmanagementsystem.Login_Form;

/**
 *
 * @author cex
 */
public class Admin_MainForm extends javax.swing.JFrame {

    /**
     * Creates new form Patient_MainForm
     */
    public Admin_MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton_AddPatient = new javax.swing.JButton();
        jButton_RemoveSecretary = new javax.swing.JButton();
        jButton_ProvideFeedback = new javax.swing.JButton();
        jButton_AddDoctor = new javax.swing.JButton();
        jButton_AddSecretary = new javax.swing.JButton();
        jButton_RemoveDoctor = new javax.swing.JButton();
        jButton_Back = new javax.swing.JButton();
        jButton_ViewRatings = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Admin");

        jButton_AddPatient.setText("Add Patient");
        jButton_AddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddPatientActionPerformed(evt);
            }
        });

        jButton_RemoveSecretary.setText("Remove Secretary");
        jButton_RemoveSecretary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveSecretaryActionPerformed(evt);
            }
        });

        jButton_ProvideFeedback.setText("Provide Feedback");
        jButton_ProvideFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProvideFeedbackActionPerformed(evt);
            }
        });

        jButton_AddDoctor.setText("Add Doctor");
        jButton_AddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddDoctorActionPerformed(evt);
            }
        });

        jButton_AddSecretary.setText("Add Secretary");
        jButton_AddSecretary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddSecretaryActionPerformed(evt);
            }
        });

        jButton_RemoveDoctor.setText("Remove Doctor");
        jButton_RemoveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RemoveDoctorActionPerformed(evt);
            }
        });

        jButton_Back.setText("Back");
        jButton_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BackActionPerformed(evt);
            }
        });

        jButton_ViewRatings.setText("View Ratings");
        jButton_ViewRatings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ViewRatingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jButton_Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButton_AddDoctor))
                    .addComponent(jButton_AddSecretary, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_RemoveDoctor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ViewRatings, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_ProvideFeedback)
                    .addComponent(jButton_RemoveSecretary)
                    .addComponent(jButton_AddPatient))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddPatient)
                    .addComponent(jButton_AddDoctor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_AddSecretary)
                    .addComponent(jButton_ProvideFeedback))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_RemoveSecretary)
                    .addComponent(jButton_RemoveDoctor))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton_Back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton_ViewRatings)))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddDoctorActionPerformed
        AddDoctor_Admin_Form pmf = new AddDoctor_Admin_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_AddDoctorActionPerformed

    private void jButton_RemoveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveDoctorActionPerformed
        RemoveDoctor_Admin_Form pmf = new RemoveDoctor_Admin_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_RemoveDoctorActionPerformed

    private void jButton_AddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddPatientActionPerformed
        AddPatient_Form pmf = new AddPatient_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_AddPatientActionPerformed

    private void jButton_AddSecretaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddSecretaryActionPerformed
        AddSecretary_Admin_Form pmf = new AddSecretary_Admin_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_AddSecretaryActionPerformed

    private void jButton_RemoveSecretaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RemoveSecretaryActionPerformed
        RemoveSecretary_Form pmf = new RemoveSecretary_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_RemoveSecretaryActionPerformed

    private void jButton_ProvideFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProvideFeedbackActionPerformed
        ProvideFeedback_Admin_Form pmf = new ProvideFeedback_Admin_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_ProvideFeedbackActionPerformed

    private void jButton_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BackActionPerformed
        setVisible(false);
        Login_Form pmf = new Login_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_BackActionPerformed

    private void jButton_ViewRatingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ViewRatingsActionPerformed
        ViewRatings_Admin_Form pmf = new ViewRatings_Admin_Form();
        pmf.setVisible(true);
    }//GEN-LAST:event_jButton_ViewRatingsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_AddDoctor;
    private javax.swing.JButton jButton_AddPatient;
    private javax.swing.JButton jButton_AddSecretary;
    private javax.swing.JButton jButton_Back;
    private javax.swing.JButton jButton_ProvideFeedback;
    private javax.swing.JButton jButton_RemoveDoctor;
    private javax.swing.JButton jButton_RemoveSecretary;
    private javax.swing.JButton jButton_ViewRatings;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
